version: '2.4'
services:
  postgres-db:
    image: postgres
    #ports:
    #  - 5432:5432
    networks:
      - zitiblue
    volumes:
     # Uncomment to save sql data between container restarts
     # - ./data/db:/var/lib/postgresql/data
      - ./postgres-bootstrap.sh:/docker-entrypoint-initdb.d/postgres-bootstrap.sh
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  ziti-tunneler:
    image: 'netfoundry/ziti-tunnel:latest'
    depends_on:
      - ziti-edge-router
    networks:
      - zitiblue
    volumes:
      - .:/netfoundry
    environment:
      - NF_REG_NAME=database
    command:
      - host

volumes:
  postgres-fs:
