name: Publish Release

on:
  create:
    tags:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.GITHUB_RUN_NUMBER }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Build with Gradle
        run: ./gradlew build assemble
      - run: ls  ${{ runner.workspace }}/build/libs/
      - run: ls  ${{ runner.workspace }}/build/libs/
      - run: find ${{ runner.workspace }} -name *.jar
      - name: Upload the jar to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ runner.workspace }}/build/libs/*.jar
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
