name: Publish Release

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.GITHUB_RUN_NUMBER }}

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: gradle
      - name: Show Info
        run: ./gradlew :showInfo
      - name: Build with Gradle
        run: ./gradlew build assemble
      - name: Upload the jar to the release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: build/lib/*          
          tag: ${{ github.ref }}
          overwrite: true
          file_glob: true
